# first we need to decide whic os we need (for ex : linux)
#NEXT WE NEED JSK/JRE TO RUN our java code
# Then we need to feed the comanmd to run our java code

#From alpine:

FROM openjdk:17-jdk-alpine
COPY HelloWorld.class . 
CMD java HelloWorld